let nombre = "Ricardo"
let apellido = "Leon"
const estudiante = nombre.concat(" ").concat(apellido)
let estudianteMayus = estudiante.toUpperCase()
let estudianteMinus = estudiante.toLowerCase()
let numLetras = estudiante.length
let primLetra = nombre.charAt()
let ulrimLetra = apellido[3]
let sinEspacios = estudiante.trim()
let contieneNombre = estudiante.includes("Ricardo")